### ISSUE TITLE
Login Failed at China

### ISSUE THREAD

**Issue by MilkyWayne** [Kemmey/Kemmey-TeslaWatch-Public#277]
Hi,

I’ve read your tweet and acknowledged  the new login requirements.

However,  I still can’t login from the iOS app. I click the login button in the app and a web page pop up ask for account  info. As I typed everything and clicked login, the app jump right back to starting page , ask  for login again.

My guess is, Tesla use local domain at China which is www.tesla.cn instead of www.tesla.com, so that  app built-in web browser for login did not redirect correctly.

But that’s my rough guess , please look into it.

Many Thanks .

**Comment by Kemmey** [comment]
@MilkyWayne you're absolutely correct! I'm currently looking into figuring out how to choose the China login server for the users where it is needed. Would you be interested in helping me test it out before I ship to the store?

**Comment by Kemmey** [comment]
@MilkyWayne if you want to test support for login from China, please join the TestFlight beta here: 

https://testflight.apple.com/join/FdzFOLZv

I just released an update with - I hope - support for logging in from China.

**Comment by MilkyWayne** [comment]
@Kemmey Thanks a lot for replying in such a short time. I've joined the TestFlight beta and currently I'm using v.1.1.4 build 437. Unfortunately, the issue remains the same. It seems the login page still redirected to US server and after I typed everything the app just went back to starting page.

**Comment by Kemmey** [comment]
Hey @MilkyWayne 

If you go to a browser and open up https://auth-global.tesla.com/oauth2/v3/token - where does that take you?

What I basically do is I send a request to that url, and then determine where it sends you - and use that url for issuing the token. 

I've made a really simple app just for issuing tokens - would you mind joining that TestFlight as well - and possibly help me iterate on the solution? I have no way to test, as I can't vpn into china :-(

https://testflight.apple.com/join/jTixIetK

**Comment by MilkyWayne** [comment]
@Kemmey 

Hi Kim,

The link “https://auth-global.tesla.com/oauth2/v3/token” will just take me to https://auth.tesla.com/oauth2/v3/token, and below is the information on web page.

{“error”:”unauthorized_client”,”error_description”:”Unauthorized client”,”error_uri”:”https://auth.tesla.com/error/reference/937b42c9-f5ef-4736-8c20-000bd74bef78-1612537648131”}

If I login my account in Tesla website here in China (Tesla.cn), the login url is "https://auth.tesla.cn/oauth2/v1/authorize?client_id=teslaweb-cn&response_type=code&scope=openid%20email%20profile&redirect_uri=https%3A//www.tesla.cn/openid-connect/generic&state=__n6HCYxwgflUTcfgOqCe3zYiEYLHnNk2gL45qByOZQ&locale=zh-CN”. 
And if I go to Tesla US website (Tesla.com) and login my account, the website will take me back to homepage just like the WatchforTesla app. 

I’ve also tried your app for issuing token, the version is V1.0 build 2. Sadly, the issue remains the same and the app acts exactly like the WatchforTesla app in iOS. 

I’m happy to test future updates in China, please let me if there is new updates.

**Comment by Kemmey** [comment]
@MilkyWayne 

Awesome! Thanks! That was super helpful! If even Tesla.com breaks, I see no other solution than a region picker, where you'll have to choose China before tapping login :-(

I would very much prefer to have that be automatic, but alas...

**Comment by Kemmey** [comment]
Hey @MilkyWayne - can you check the auth app in TestFlight if it allows you to login to the China region now?

**Comment by MilkyWayne** [comment]
@Kemmey 

Hi Kim，

I’m happy to say, the Watch app for Tesla on iOS (build 438) works as expected and it can transfer login to Watch app without any problem. 

As for the Auth app for Tesla (build 3), there will be new options of “Refresh token” and “Access token” after login. It seems the new region picker is a good way to differ Global account and China account.

Thanks a lot for the great effort. 

Wish you all the best.
