### ISSUE TITLE
Complication displays all showing as dashed lines

### ISSUE THREAD

**Issue by Flybuddy** [Kemmey/Kemmey-TeslaWatch-Public#385]
Iphone 12 and Watch series 6, had issues with the displayed complication being a still photo and not changing or matching the actual state of charge. Spent several hours deleting and reinstalling app and all complications while booting at each phase to no avail. All complications now simply showing as dashed lines. Any suggestions as to how to fix appreciated..thx
![IMG_8326](https://user-images.githubusercontent.com/74599376/127868629-aa3902e4-a29d-4a32-8e10-1b9077147e45.JPG)
![IMG_8325](https://user-images.githubusercontent.com/74599376/127868639-8e43fc02-0bd5-46c1-bb43-11dc82f2626e.JPG)

**Comment by Kemmey** [comment]
@Flybuddy am I correct in assuming watchOS 7.6 or 7.6.1?

What build of the app?

**Comment by Flybuddy** [comment]
Apologize for having 2 issues on Github, really same problem. Yes, I did delete everything and build comps back one at a time (with reboots) and that's where it went from fields that showed static data that didn't change to all dashes across the board. Watch OS is 7.6.1 and the app is 1.1.8 build # 783..thx for any help

    On Monday, August 2, 2021, 9:24:55 AM EDT, Kim Hansen ***@***.***> wrote:  
 
 


@Flybuddy am I correct in assuming watchOS 7.6 or 7.6.1?

What build of the app?

**Comment by Flybuddy** [comment]
Tried reloading the comps and booting watch again and this time it worked. Tested functions and all ok. 

    On Monday, August 2, 2021, 9:24:55 AM EDT, Kim Hansen ***@***.***> wrote:  
 
 


@Flybuddy am I correct in assuming watchOS 7.6 or 7.6.1?

What build of the app?

**Comment by zwuba** [comment]
Hi Kim!
I can’t get rid of this issue not even by uninstalling everything and reinstall!
I tried the beta 1.1.9 and the released 1.1.8

I already sent you an eMail which your spam might have eaten up …

let me know if you need more information or how I can fix it?!

thx a lot

**Comment by Kemmey** [comment]
Hey @zwuba 

I checked my mail and spam and didn't find any mails I've not responded to - could you try just sending a hello mail to see if there's an issue with receiving? (That would be disastrous for me if that was the case and people could not get help!)

waft@kimhansen.dk

As for the issue - there's not much I can do, as the issue lies with watchOS 7.6 / 7.6.1 - as you can see above, it does take some tries to fix it - remove all complications, uninstall app, restart both phone and watch at this point. Then reinstall app and add complications one by one and let them update and settle in before adding more. 

Fingers crossed. I'm really sorry for this, but it doesn't seem to be affecting a particular version of my app - and in my case it affects both apples own and other 3rd parties alike. Completely at random. 

My best guess is that they adjusted the allowed power budget for complications processing, so the watchdog kills complication processing during initialization and then it just never recovers as this is cached indefinitely. At least that's what it looks like to me. When in this state, no code of mine is ever executed. watchOS just does not even call into my app to refresh the complication or even grab the initial template or preview.

**Comment by zwuba** [comment]
Thanks Kim - will try :)

Already sent an eMail to your given address so you can check if everything is fine there too.

**Comment by Kemmey** [comment]
@zwuba Email received! Thanks! :-D

**Comment by thumbmaster** [comment]
We tried deleting the apps from the phone and watch, rebooted both, reinstalled. Most of the complications are still showing up as dashes...  :-(

**Comment by Kemmey** [comment]
I really hope these complication issues are fixed by Apple in watchOS 8. I myself continue to also have issues - usually around updating the app, it will take a couple of hours until complications again start updating. 

This is so far only on watchOS 7.6 and 7.6.1

**Comment by vchang-hc** [comment]
Yeah, upgrading both my iPhone 11 Pro Max to iOS15 and Apple Watch to iOS WacthOS 8 didn't fix this battery not updating issue yet.

**Comment by Kemmey** [comment]
@vchang-hc ok, that's disconcerting. 

Are the complications stuck at 75% or do they show the dashed lines?

Does the app itself show the proper values?

Does the data age indicator on the complications properly reset? (Please try with a complication that has the data age indicator feature)

Finally - please show me what watch face and complication slot you're using - I might have missed a combination. 

Cheers,

Kim

**Comment by vchang-hc** [comment]
Not stuck at 75%.  Both the phone and the Watch app are giving the same Battery % / miles left.  This is diff. from what the Car or the actual Tesla app is showing.  for example:

Tesla App: 182mi 
Your Watch / App: 79% 161mi

This is the same on all the watch faces I have.  But I'm using the Chronograph Pro on my Apple Watch 4

The data age indicator on the complication properly reset.  

Hope this helps.  Love your app btw.  

best regards,
Vindi

**Comment by Kemmey** [comment]
Hey @vchang-hc 

Sorry for the late response. 

Could you check the advanced settings and ensure "Override vehicle unit" is not toggled on? I might have shipped that as enabled by default, per some accounts...

**Comment by vchang-hc** [comment]
yup, that was it.  Thx.

**Comment by Dot-Dash** [comment]
I am also seeing this problem (all dashed lines in complication). Watch for Tesla v. 1.2.2 build 933. Series 4 watch, Watch OS 8.3 (19S55).  iPhone 11 Pro, iOS version 15.2.1.  I was able to recover from this at least once without re-installing the app. I believe I restarted the Watch and maybe the iPhone.  The weird thing is, if I tap the complication to open the app, all information is there, and up-to-date.
![incoming-10B87C84-B4F3-4E07-9BB1-B7EE6C363A23](https://user-images.githubusercontent.com/6632885/149980555-33a9b7ce-96c8-4b0c-b2ef-2b228f010699.PNG)

**Comment by Kemmey** [comment]
@Dot-Dash yeah - and you'll also sometimes see this error only in the "ON" state - so if you have a watch with always-on display, when the display is in the "off" dimmed mode - the complication will show up correctly. Further proving that this is a watchOS bug - and not anything that I can work around. And believe me - I've tried to work around this bug since it was introduced in watchOS 7.6.2 :-(

**Comment by Dot-Dash** [comment]
I confirm that restarting the watch has cleared the problem for me a couple of times now.  I think we should be curious as to what circumstance triggers the dashed-lines-mode to start. I have it operate correctly for at least a couple of days before entering the failure mode. But I don't know what was different when it decided to fail.
